import type { Metadata } from "next";
import {
  Bricolage_Grotesque,
  DM_Sans,
  Montserrat,
  Space_Grotesk,
  Sansation,
  Tomorrow,
} from "next/font/google";
import "./globals.css";
import ReactQueryProviders from "@/lib/core/components/providers/tanstack/react-query";
import { ThemeProvider } from "@/lib/core/components/providers/theme/theme-provider";

const spaceGrotesk = Space_Grotesk({
  variable: "--font-space-grotesk",
  subsets: ["latin"],
  display: "swap",
  fallback: ["sans-serif"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={spaceGrotesk.className}>
      <body className="font-space-grotesk">
        <ReactQueryProviders>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider>
        </ReactQueryProviders>
      </body>
    </html>
  );
}
